### ISSUE TITLE
Simple usage without a build?

### ISSUE THREAD

**Issue by kaihendry** [djthorpe/ytapi#2]
Hi David,

I have an API key "SECRET" and channel ID, UCFzGyNKXPAglNq28qWYTDFA and I want to use your cli to list all my videos. Hoping it will do that without me having to worry about that bothersome nextPageToken stuff.

However I'm struggling to find a client_secret.json example?

Would it be more natural to `go install` the cli and have a default like `~/.ytapi/credentials`?

My use case is build a list of my videos so I can back them up. Thank you!

**Comment by djthorpe** [comment]
Hi Kai! You should create a developer account for yourself on https://console.developers.google.com and then create a project for the tool. You can then create "Credentials" and download the client_secrets.json file.

Also remember to enable the YouTube API's within your project - the link for that is

https://console.developers.google.com/apis/library

Let me know if you need any more help.

**Comment by kaihendry** [comment]
Little confused about the roles: https://s.natalian.org/2017-09-11/ytapi.mp4

**Comment by djthorpe** [comment]
My apologies Kai. Thanks for your video. In fact if you only want the client_secrets.json file, then you don't need the service account flow. I've created a counterpart video here:

https://github.com/djthorpe/ytapi/blob/master/doc/Creating%20a%20client%20secrets%20file.mov?raw=true

**Comment by djthorpe** [comment]
Will close this issue now, please let me know if you need any more help!
